name: freezed_mappable

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  dart_mappable: ^2.0.0
  freezed_annotation: ^2.2.0

dev_dependencies:
  build_runner: ^2.2.0
  dart_mappable_builder: ^2.0.0
  freezed: ^2.2.0
  lints: ^2.0.1