name: dart_mappable_builder
description: Improved json serialization and data classes with full support for generics, inheritance, customization and more.
version: 3.0.3-dev.2
repository: https://github.com/schultek/dart_mappable
issue_tracker: https://github.com/schultek/dart_mappable/issues
funding:
  - https://github.com/sponsors/schultek
publish_to: none

environment:
  sdk: '>=2.17.0 <4.0.0'

dependencies:
  analyzer: ^5.2.0
  ansicolor: ^2.0.1
  build: ^2.0.0
  collection: ^1.15.0
  dart_mappable:
    git:
      url: https://github.com/devfelipereis/dart_mappable
      path: packages/dart_mappable
      ref: v3.0.3-dev.2
  dart_style: ^2.2.4
  glob: ^2.1.0
  path: ^1.8.0
  source_gen: ^1.2.5

dev_dependencies:
  build_runner: ^2.2.0
  build_test: ^2.1.5
  lints: '>=1.0.0 <3.0.0'
  test: ^1.22.1
