name: fic_mappable

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  dart_mappable: any
  fast_immutable_collections: ^7.4.1

dev_dependencies:
  build_runner: ^2.2.0
  dart_mappable_builder: any
  lints: ^2.1.0
