name: dart_mappable
description: Improved json serialization and data classes with full support for generics, inheritance, customization and more.
version: 2.0.3
repository: https://github.com/schultek/dart_mappable
issue_tracker: https://github.com/schultek/dart_mappable/issues
documentation: https://pub.dev/documentation/dart_mappable/latest/topics/Introduction-topic.html
funding:
  - https://github.com/sponsors/schultek
publish_to: none

environment:
  sdk: '>=2.17.0 <3.0.0'

dependencies:
  collection: ^1.15.0
  meta: ^1.8.0
  type_plus: ^1.0.0

dev_dependencies:
  build_runner: ^2.2.0
  dart_mappable_builder:
    git:
      url: https://github.com/devfelipereis/dart_mappable
      ref: feat/custom-property
      path: packages/dart_mappable_builder
  lints: '>=1.0.0 <3.0.0'
  test: ^1.20.1
